### ISSUE TITLE
split container + richTextBox

### ISSUE THREAD

**Issue by olegzig** [olegzig/Converter#3]
when we move spliter, scrollBars in RichTextBox does not appear, so, hyphenation doesnt work

**Comment by olegzig** [comment]
Для того чтобы пофиксить, нужно подогнать размер внутреннего окна под размер размер родительского
https://www.cyberforum.ru/windows-forms/thread2743401.html
Тут структурировал что получилось

**Comment by Bandforr** [comment]
Stupid
